#version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: concert-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    command: --innodb_redo_log_capacity=1G
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data/mysql/:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: concert-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

networks:
  default:
    driver: bridge