spring:
  application:
    name: concert
  profiles:
    active: local

springdoc:
  api-docs:
    path: /api-docs     # default is /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /api-docs       # point the UI at your new spec URL
    tagsSorter: none
    operationsSorter: none


---
spring.config.activate.on-profile: local, test